---
openapi: 3.0.1
info:
  title: Review-api
  version: v0
  description: Review REST API.
servers:
- url: http://localhost:8083/api/v1
  description: Generated server url
paths:
  /reviews/{id}:
    summary: Get and delete review.
    get:
      tags:
      - review-service-impl
      parameters:
      - name: id
        schema:
          format: int32
          type: integer
        in: path
        required: true
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
              examples:
                GetReview:
                  value:
                    reviewID: 50
                    productID: 50
                    author: rudysaniez
                    subject: Nice
                    content: Beautiful! it works
                    creationDate: 2020-11-19T16:53:11
          description: OK
      operationId: getReview
      summary: Get a review by ID.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
            examples:
              UpdateReview:
                value:
                  reviewID: 50
                  productID: 50
                  author: rudysaniez
                  subject: Nice
                  content: Beautiful! it works
        required: true
      tags:
      - review-service-impl
      parameters:
      - name: id
        description: Review identifier.
        schema:
          format: int32
          type: integer
        in: path
        required: true
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: OK
      operationId: update
      summary: Update a review.
    delete:
      tags:
      - review-service-impl
      parameters:
      - name: id
        description: Review identifier.
        schema:
          format: int32
          type: integer
        in: path
        required: true
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          description: OK
      operationId: deleteReviews
      summary: Delete a review.
    parameters:
    - name: id
      description: Review identifier.
      schema:
        format: int32
        type: integer
      in: path
      required: true
  /reviews:
    summary: Get and create review.
    get:
      tags:
      - review-service-impl
      parameters:
      - name: productId
        description: product identifier.
        schema:
          format: int32
          type: integer
        in: query
        required: true
      - name: pageNumber
        description: Page number.
        schema:
          format: int32
          type: integer
        in: query
        required: false
      - name: pageSize
        description: Page size.
        schema:
          format: int32
          type: integer
        in: query
        required: false
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedReview'
              examples:
                GetReviewByProductID:
                  value:
                    content:
                    - reviewID: 50
                      productID: 50
                      author: rudysaniez
                      subject: Nice
                      content: Beautiful! it works
                      creationDate: 2020-11-19T16:53:11
                    page:
                      size: 10
                      totalElements: 1
                      totalPages: 1
                      number: 0
          description: OK
      operationId: getReviewByProductId
      summary: Get a review by productID.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
            examples:
              CreateReview:
                value:
                  reviewID: 50
                  productID: 50
                  author: rudysaniez
                  subject: Nice
                  content: Beautiful! it works
        required: true
      tags:
      - review-service-impl
      responses:
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
          description: Unprocessable Entity
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
              examples:
                ReviewCreated:
                  value:
                    reviewID: 50
                    productID: 50
                    author: rudysaniez
                    subject: Nice
                    content: Beautiful! it works
                    creationDate: 2020-11-19T16:53:11
          description: Created
      operationId: save
      summary: Create a review.
components:
  schemas:
    HttpErrorInfo:
      type: object
      properties:
        timestamp:
          format: date-time
          type: string
        path:
          type: string
        httpStatus:
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
          type: string
        message:
          type: string
    Review:
      type: object
      properties:
        reviewID:
          format: int32
          type: integer
        productID:
          format: int32
          type: integer
        author:
          type: string
        subject:
          type: string
        content:
          type: string
        creationDate:
          format: date-time
          type: string
        updateDate:
          format: date-time
          type: string
    PageMetadata:
      type: object
      properties:
        size:
          format: int64
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int64
          type: integer
        number:
          format: int64
          type: integer
    PagedReview:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Review'
        page:
          $ref: '#/components/schemas/PageMetadata'
